import React from "react";
import ReactDOM from "react-dom/client";
import { Provider } from "react-redux";
import { BrowserRouter } from "react-router-dom";
import { GoogleOAuthProvider } from "@react-oauth/google";
import App from "./App.jsx";
import { store } from "./app/store.js";
import "./index.css";
const googleClientId = import.meta.env.VITE_GOOGLE_CLIENT_ID || "";
ReactDOM.createRoot(document.getElementById("root")).render(<React.StrictMode><GoogleOAuthProvider clientId={googleClientId}><Provider store={store}><BrowserRouter><App /></BrowserRouter></Provider></GoogleOAuthProvider></React.StrictMode>);
